#!/bin/zsh
cargo run > output_tmp.json
cat output_tmp.json | sed -e s'#\\##g' | sed -e 's/\"{/{/g' | sed -e 's/}\"/}/g' > output20220909.json
gsutil cp /Users/syu/toy-crawler/src/output20220909.json gs://testhosting202209
gsutil setmeta -h "Cache-Control: public, no-store" gs://testhosting202209/output20220909.json
gsutil setmeta -h "Content-Language:en" gs://testhosting202209/output20220909.json
rm output_tmp.json
